# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Build Nucleus 3

on:
  push:
    branches:
      - v3

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build
    - name: Publish to repositories
      run: ./gradlew publish

    - name: Upload Plugin
      uses: actions/upload-artifact@v2
      with:
        name: Nucleus Plugin
        path: output/*-plugin.jar
    - name: Upload API
      uses: actions/upload-artifact@v2
      with:
        name: Nucleus API
        path: output/*-API.jar
    - name: Upload Javadocs
      uses: actions/upload-artifact@v2
      with:
        name: Nucleus Javadocs
        path: output/*-javadocs.jar
    - name: Upload Release Notes
      uses: actions/upload-artifact@v2
      with:
        name: Release Notes
        path: output/*.md
